### ISSUE TITLE
Query rawhide

### ISSUE THREAD

**Issue by hroncok** [asamalik/modular-repoquery#1]
How do I query rawhide? I have no modular updates repo for rawhide.

**Comment by asamalik** [comment]
That's a very good question. It would be best if we could somehow convince it to expand the flag to all modular repos instead of listing them manually. Or just do an `if rawhide`, it's a horrible shell script  workaround anyway... :-)

**Comment by hroncok** [comment]
I don't run rawhide (not now anyway). I want to query it. The check for /etc/fedora-release is too naive.

<del>Also, where do I get the rawhide-modular repo file from?</del>

**Comment by hroncok** [comment]
For illustration, this is how I query nonmodular rawhide now:

```
$ dnf repoquery --repo=rawhide  --repo=rawhide-source --whatrequires python2-toscawidgets
```

And the repo file is from fedora-repos-rawhide package. That also seem to contain rawhide-modular \o/

**Comment by asamalik** [comment]
So I just tested that setting a non-existing repo as a hotfix repo won't result in an error.

So in theory I could just use `--setopt=updates-modular.module_hotfixes=true --setopt=fedora-modular.module_hotfixes=true --setopt=rawhide-modular.module_hotfixes=true repoquery` for all queries, and that should also work with your example.

**Comment by hroncok** [comment]
Nice. Does it work for sources?

Aka can I query that modular python-django BRs python2-devel?

https://src.fedoraproject.org/rpms/python-django/blob/1.6/f/python-django.spec

**Comment by asamalik** [comment]
It should. Try now?

BTW there is a bug in DNF that causes it to throw errors like "nothing provides platform:f30" when querying different repos. So `2>/dev/null` might be your friend here. :-)

**Comment by asamalik** [comment]
`./modular-repoquery --repo=rawhide --repo=rawhide-modular --whatprovides /usr/bin/npm 2>/dev/null` for example

**Comment by hroncok** [comment]
Getting some results:

```
$ ./modular-repoquery --repo=rawhide-source --repo=rawhide-modular-source --whatrequires python2-devel 2>/dev/null | grep django
python-django-0:1.6.11.7-3.module_2144+ff35d33b.src 
python-django-braces-0:1.12.0-3.module_2438+0f557a29.src 
python-django-cors-headers-0:1.1.0-1.module_2438+0f557a29.src 
python-django-evolution-1:0.7.7-12.module_1631+4353a891.src 
python-django-evolution-1:0.7.7-13.module_2438+0f557a29.src 
python-django-multiselectfield-0:0.1.3-10.module_1631+4353a891.src 
python-django-multiselectfield-0:0.1.3-10.module_2438+0f557a29.src 
python-django-nose-0:1.4.5-6.fc29.src
python-django-oauth-toolkit-0:0.9.0-3.module_2438+0f557a29.src 
python-django-pipeline-0:1.3.27-11.module_1631+4353a891.src 
python-django-pipeline-0:1.6.14-2.module_2438+0f557a29.src 
python2-django1.11-0:1.11.18-1.fc30.src
```

It doesn't show the module for source packages.

**Comment by asamalik** [comment]
I think that's because source packages are not part of a module as far as the metadata go... :/

**Comment by hroncok** [comment]
That's a bummer. But I guess the release dist tag kinda gives that away :D

**Comment by hroncok** [comment]
Thanks for help.

**Comment by asamalik** [comment]
The release repos won't give you all the info you need anyway. https://tree.taiga.io/project/modularity-wg/us/105

I'll be working on generating repodata with all the info, including packages that have been filtered out by module filters and buildroot-only modules. I'll see if I can somehow add modulemd files for the SRPMs as well.

**Comment by asamalik** [comment]
You're welcome!
